### ISSUE TITLE
competitive scenario

### ISSUE THREAD

**Issue by saizhang0218** [oxwhirl/smac#19]
Does SMAC support competitive MARL? That is, I want to implement two MARL algorithms to compete with each other, rather than the user agents compete with build-in AI. If yes, is there any guide on how to modify the code? Thanks!

**Comment by PaLeroy** [comment]
Hey,
You can have a way to do it on my forked repo. It is certainly not the nicest way but it works well.

Basically, you need to run a sc2 client for each team you want to control, manage multiple teams in the several SMAC functions and, of course, modify the maps in the map editor.

**Comment by samvelyan** [comment]
Competitive scenarios are currently not supported in SMAC. There are no immediate plans for adding the support for them as well.

However, SMAC code **can be modified** to allow two MARL algorithms fight each other. Should you wish to do this, I'll be more than happy to help.

**Comment by LeejwUniverse** [comment]
HI, @samvelyan I would like to edit code allowing two MARL algorithms for fighting each other. could you give me the information on editing code in SMAC?

**Comment by PaLeroy** [comment]
Hey, I modified SMAC to allow competition of two teams [(my fork)](https://github.com/PaLeroy/smac/blob/master/smac/env/starcraft2/starcraft2multi.py).
I based my implementation on [pysc2](https://github.com/deepmind/pysc2/blob/master/pysc2/env/sc2_env.py).
The idea is to create two sc2 processes that join the same sc2 game. You therefore need to play a bit with the sc2 editor to modify maps.
In the future I might consider to adapt the implementation in order to control all agents with a single sc2 process, which would be more stable.

**Comment by PaLeroy** [comment]
Never tried but it might be possible to beat them, depending on the training scenario and generalisation capabilities of the trained teams.

**Comment by LeejwUniverse** [comment]
Thanks for your kindness. I will try to train my algorithm based on your repo.
