### ISSUE TITLE
How to stop an episode after a number of steps and still receive negative reward

### ISSUE THREAD

**Issue by douglasrizzo** [oxwhirl/smac#47]
Hi there. I was wondering if there is a way to end an episode after a certain number of steps, ensuring the agents receive the proper negative reward for failing. I was doing it manually by counting the number of steps in my own loop and calling `env.reset()` after a set number of steps, but this way I don't get a properly subtracted/scaled reward from the environment.

**Comment by samvelyan** [comment]
You can modify the episode `limit` for each map in [smac_maps.py](https://github.com/oxwhirl/smac/blob/master/smac/env/starcraft2/maps/smac_maps.py).

**Comment by douglasrizzo** [comment]
Thanks for pointing that out. Is there a reason why each map has a different step limit?

**Comment by samvelyan** [comment]
Well, some of the maps/scenarios are easy and winning policies take a small number of steps. If so, we want to restart the episodes frequently in case no progress is being made - so that the learning takes less time. On the other hand, some of the maps take longer to master and winning policies take a larger number of steps (e.g. 3s_vs_5z).
